var Images_array = new Array(
'abort.gif',
'admin.gif',
'aree.gif',
'arrow.gif',
'arrow_down.gif',
'arrow_sel.gif',
'autopay.gif',
'autopay_sel.gif',
'check_on.gif',
'check_on_sel.gif',
'construction.gif',
'cp.gif',
'cp_line.gif',
'cp_tools.gif',
'devider.gif',
'gethtml.gif',
'help.gif',
'history.gif',
'howtostart.gif',
'infedit.gif',
'infedit_sel.gif',
'info.gif',
'info_m.gif',
'ledoff.gif',
'ledoff_sel.gif',
'ledon.gif',
'ledon_sel.gif',
'listings.gif',
'logout1.gif',
'm_head.gif',
'm_head_btn_down.gif',
'm_head_btn_up.gif',
'mail.gif',
'mail_confirm.gif',
'mail_confirm_sel.gif',
'mail_not_confirm.gif',
'mail_not_confirm_sel.gif',
'page_go.gif',
'page_go_sel.gif',
'password.gif',
'preview.gif',
'preview_sel.gif',
'profile.gif',
'reject.gif',
'reject_sel.gif',
'reject2.gif',
'reject2_sel.gif',
'request.gif',
'settings1.gif',
'show-calendar1.gif',
'sortasc.gif',
'sortdesc.gif',
'spacer.gif',
'stats.gif',
'up.gif',
'up_sel.gif',
'users.gif',
'vdevider.gif',
'welcome.gif'
);
var Images = [];

for (var i=0; i<Images_array.length; i++)
{
	Images[i] = new Image();
	Images[i].src = "images/"+Images_array[i];
}